- name: Ensure Docker and Docker Compose are installed
  hosts: all
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: true
      changed_when: false

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_installed
      ignore_errors: true
      changed_when: false

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      when: docker_compose_installed.rc != 0
