---
- name: Ensure Docker and Docker Compose are installed
  hosts: all
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed|failed

    - name: Check if Docker.io is installed
      command: docker.io --version
      register: docker_io_installed
      ignore_errors: true

    - name: Install Docker.io
      apt:
        name: docker.io
        state: present
      when: docker_io_installed|failed

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_installed
      ignore_errors: true

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      when: docker_compose_installed|failed
