- hosts: all
  environment:
    LC_ALL: "en_US.UTF-8"
  become: yes
  tasks:
    - name: Get list of packages to be upgraded
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
        list: yes
      register: apt_upgrade_result

    - name: Display packages to be upgraded
      debug:
        msg: "Packages to be upgraded: {{ apt_upgrade_result.package_list }}"

    - name: Perform apt upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Run apt autoremove
      become: yes
      apt:
        autoremove: yes
        autoclean: yes

    - name: Fetch list of autoremovable packages
      shell: apt-get -s autoremove | awk '/^Remv/ { print $2 }'
      register: autoremove_list

    - name: Display autoremovable packages
      debug:
        msg: "Autoremovable packages: {{ autoremove_list.stdout_lines }}"
