- hosts: all
  environment:
    LC_ALL: "en_US.UTF-8"
  become: yes
  tasks:
    - name: Perform apt update
      apt:
        update_cache: yes

    - name: Perform apt upgrade
      apt:
        upgrade: yes

    - name: Fetch list of autoremovable packages
      shell: apt-get -s autoremove | awk '/^Remv/ { print $2 }'
      register: autoremove_list

    - name: Display autoremovable packages
      debug:
        msg: "Autoremovable packages: {{ autoremove_list.stdout_lines }}"

    - name: Remove autoremovable packages
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ autoremove_list.stdout_lines }}"
