- hosts: all
  environment:
    LC_ALL: "en_US.UTF-8"
  become: yes
  tasks:
    - name: Perform apt update
      apt:
        update_cache: yes

    - name: Get list of packages to be upgraded
      command: apt list --upgradable
      register: apt_upgrade_result
      changed_when: false

    - name: Display packages to be upgraded
      debug:
        msg: "Packages to be upgraded: {{ apt_upgrade_result.stdout_lines }}"

    - name: Perform apt upgrade
      apt:
        upgrade: yes

    - name: Run apt autoremove
      apt:
        autoremove: yes
        autoclean: yes

    - name: Fetch list of autoremovable packages
      shell: apt-get -s autoremove | awk '/^Remv/ { print $2 }'
      register: autoremove_list

    - name: Display autoremovable packages
      debug:
        msg: "Autoremovable packages: {{ autoremove_list.stdout_lines }}"
