---
- hosts: all
  environment:
    LC_ALL: "en_US.UTF-8"
  become: yes
  tasks:
      - name: upgrade apt packages
        become: true
        apt:
          upgrade: yes
          update_cache: yes
